### PR TITLE
fix to work on browser

### PR DESCRIPTION
**Pull request by ghost**
Somehow the package name was wrong and it was not working in the browser. 

I'm sorry if it was my misunderstanding.

thanks.

### CODE REVIEW

**Comment by oscarotero** [comment]
Ok, I see.
The problem is that the same package has different names in bower and npm:
https://github.com/alexei/sprintf.js
In bower is registered as `sprintf` and in npm is `sprintf-js`. I've always related bower with AMD and npm with commonJS. This is why I use different names depending of the type of the module.

How are you loading this package?

**Comment by ghost** [comment]
well... At first I did

```
npm install --save gettext-translator
```

and I wrote this.

```js
import Translator from 'gettext-translator'
```

but when I build it with webpack, it say 

```
ERROR in ./node_modules/gettext-translator/src/translator.js
Module not found: Error: Can't resolve 'sprintf'
```

so I think that "Maybe If I change sprintf to sprintf-js, it will work". and it was correct.

Am I misunderstanding how to use it?

**Comment by oscarotero** [comment]
Your code is correct. The problem is webpack is loading the package as AMD and in AMD the package is named `printf` (because it's assumed to be installed with bower).
Maybe, a solution could be remove bower support.

Meanwhile, can you test if this works fine (load the library as CommonJS instead ES6)?:
```js
var Translator = require('gettext-translator');
```

**Comment by ghost** [comment]
thanks. I tested your code.

```js
const Translator = require('gettext-translator');
```

but webpack says same error again...

**Comment by ghost** [comment]
and I tried

```console
bower install gettext-translator 
```

but now webpack says

```
Module not found: Error: Can't resolve 'script-loader'
```

**Comment by ghost** [comment]
I found that

```js
console.info(!!(typeof define === "function" && define.amd));
console.info(!!(typeof module === "object" && module.exports));
```

output 

```
true
true
```

so I changed priority.

How do you feel ?

**Comment by oscarotero** [comment]
I think the problem is not in the priority, but in the different name if the package is loaded by npm or bower. I'm more inclined to your initial solution, and if the package is installed with bower, just use a [alias to the module](https://webpack.js.org/configuration/resolve/#resolve-alias). And because bower is deprecated, we can sacrifice it.

**Comment by ghost** [comment]
well... organize information.

In my project, grttext-translator is installed by npm.
so npm install sprintf-js.
but code want to define sprintf because the code misunderstands that the environment is AMD.

right ?

Although resolve.alias is certainly one solution, I think that it is not the best.

I think the real problem is the priority of AMD and CommonJS.

Why do you think the problem is not in the priority ? 

On AMD, module.exports is undefined. so I think that Changing the priority does not cause problems.

**Comment by oscarotero** [comment]
> Why do you think the problem is not in the priority ?

Because AMD/CommonJS/ES6Modules are diferent ways to load javascript modules. And Bower/NPM are diferent ways to install these modules. If the module is installed with npm, it will be named `sprintf-js`, no matter if then is loaded with amd, commonjs, or es6. With bower is the same, but the name is different.

Initially, I decided to use AMD when the package is installed with bower an commonjs when it's installed with npm. But that solution is not 100% valid (you may want to use amd with npm).

So, maybe the best solution is use only npm (bower is currently deprecated anyway). Another solution is create two different main files, one for npm and other for bower. Something like:

For npm:

```js
(function (root) {
    //amd
    if (typeof define === "function" && define.amd) {
        define(['sprintf-js', './factory'], function (sprintf, factory) {
            return factory(sprintf.vsprintf);
        });

    //commonjs
    } else if (typeof module === "object" && module.exports) {
        var factory = require('./factory');
        module.exports = factory(require('sprintf-js').vsprintf);

    //global
    } else {
        root.Translator = factory(window.vsprintf);
    }
```

For bower:

```js
(function (root) {
    //amd
    if (typeof define === "function" && define.amd) {
        define(['sprintf', './factory'], function (sprintf, factory) {
            return factory(sprintf.vsprintf);
        });

    //commonjs
    } else if (typeof module === "object" && module.exports) {
        var factory = require('./factory');
        module.exports = factory(require('sprintf').vsprintf);

    //global
    } else {
        root.Translator = factory(window.vsprintf);
    }
```

This requires to move the factory code to a different file.
What do you think?

**Comment by ghost** [comment]
https://github.com/oscarotero/gettext-translator/pull/2/commits/5968ac8542c450e7ef4604fe13bdce861eec5605
well, now this pr change it to only for npm.

**Comment by oscarotero** [comment]
Ok, thank you!

**Comment by ghost** [comment]
👍

**Comment by oscarotero** [comment]
Released the version 2.0.0 including this change.

**Pull request merged**
