### PR TITLE
getPluralIndex return value bug fixed

### PR DESCRIPTION
**Pull request by procket-org**
getPluralIndex should return index, not boolean

### CODE REVIEW

**Comment by oscarotero** [comment]
In theory, the plural function should return an integer, and not always is `0` or `1`, but in some languages there's more plurals. Are you using a correct plural funcion?

**Comment by procket-org** [comment]
`更新 %s 条: ["%s item updated", "%s items updated"]`
This is the plural translation of one item in json file, it's no working when i call n__(original, plural, value).

dnpgettext: function (domain, context, original, plural, value) {

            var index = getPluralIndex(this.plurals, domain, value);   // return boolean

            var translation = getTranslation(this.dictionary, domain, context, original);

            if (translation[index] && translation[index] !== '') {  // index not found
                return translation[index];
            }

            return (index === 0) ? original : plural;  // not translated, just return param plural
}

**Comment by oscarotero** [comment]
What I want to see is the plural function that returns a boolean instead an integer, or in other words, the content of `plurals[domain].code`

**Comment by procket-org** [comment]
When plural form is
`Plural-Forms: nplurals=2; plural=n != 1;`
The code will be 
`return n != 1;`

The doc from GNU gettext
> Two forms, singular used for one only
This is the form used in most existing programs since it is what English is using. A header entry would look like this:

Plural-Forms: nplurals=2; plural=n != 1;
(Note: this uses the feature of C expressions that boolean expressions have to value zero or one.)

**Comment by oscarotero** [comment]
Ok, understood.
Thank you! 👍

**Pull request merged**
